#!/usr/bin/env bash
#A script to install nginx web server

sudo su
apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
nginx -t
service nginx restart
