#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me
#is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/server_name _;/a \\\n    location \/redirect_me {\n        return =301 ;\n    }"
sudo nginx -t
sudo service  nginx reload
