#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string "Ceci n'est pas une page".

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Add configuration to serve the custom 404 error page
sudo sed -i "/server_name _;/a \\\n    error_page 404 \/404.html;\n    location = \/404.html {\n        internal;\n    }" /etc/nginx/sites-available/default

# Test the Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the changes
sudo service nginx reload
