#!/usr/bin/env bash
#a Bash script that displays numbers from 1 to 100 in fizzbuzz

number=1
until [ $number -eq 101 ]
do
	if (( number % 3 == 0 )) && (( number % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( number % 3 == 0 ))
	then 
		echo "Fizz"
	elif (( number % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $number
	fi
number=$((number+1))
done
