#!/usr/bin/env bash
#a Bash script that gives you information about the school file.

file=/school

if [ -e "$file" ]
then
	echo"school file exist"
	if [ -s "$file" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$file" ]
	then
		echo "school is a regular file"
	else
		echo 
	fi
else
	echo "school file does not exist"
	exit $?
fi
